matrix:
  include:
    - language: rust
      env:
        global:
        - RUST_BACKTRACE=1

      rust:
        - stable
        - beta

      matrix:
        fast_finish: true

      before_script:
        - rustup component add clippy
        - rustup component add rustfmt

      script:
        - cargo build
        - cargo clippy -- -A clippy::large_enum_variant
        - cargo fmt -- --check

    - language: node_js
      node_js:
        - 13
      before_script:
        - yarn install
        - yarn build
      script:
        - yarn test

    - language: erlang
      otp_release: 22.2
      before_ script:
        - kerl list installations

      script:
        - ./rebar3 compile
